name: Format Pull Request

on:
  push:
    branches: [main]
    paths:
      - src/**
      - .github/workflows/test.yml
  pull_request:
    branches: [main]
    paths:
      - src/**
      - .github/workflows/test.yml

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Format with rustfmt
        run: cargo fmt -- --check
